# Generated by Django 3.1.7 on 2021-03-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.team')),
            ],
            options={
                'db_table': 'game_stats',
            },
        ),
    ]
