# Generated by Django 3.1.7 on 2021-03-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
        ('game', '0001_initial'),
        ('gamestats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestats',
            options={'ordering': ['-game']},
        ),
        migrations.AlterUniqueTogether(
            name='gamestats',
            unique_together={('team', 'game')},
        ),
    ]
