# Generated by Django 3.1.7 on 2021-04-29 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_1_pts_ok', models.PositiveIntegerField(default=0, help_text='Rzuty celne za 1 pkt', verbose_name='RZ1 O')),
                ('shot_1_pts_total', models.PositiveIntegerField(default=0, help_text='Rzuty ogółem za 1 pkt', verbose_name='RZ1 T')),
                ('shot_2_pts_ok', models.PositiveIntegerField(default=0, help_text='Rzuty celne za 2 pkt', verbose_name='RZ2 O')),
                ('shot_2_pts_total', models.PositiveIntegerField(default=0, help_text='Rzuty ogółem za 2 pkt', verbose_name='RZ2 T')),
                ('shot_3_pts_ok', models.PositiveIntegerField(default=0, help_text='Rzuty celne za 3 pkt', verbose_name='RZ3 O')),
                ('shot_3_pts_total', models.PositiveIntegerField(default=0, help_text='Rzuty ogółem za 3 pkt', verbose_name='RZ3 T')),
                ('reb_def', models.PositiveIntegerField(default=0, help_text='Zbiórki obrona', verbose_name='ZB D')),
                ('reb_off', models.PositiveIntegerField(default=0, help_text='Zbiórki atak', verbose_name='ZB O')),
                ('ast', models.PositiveIntegerField(default=0, help_text='Asysty', verbose_name='AS')),
                ('stl', models.PositiveIntegerField(default=0, help_text='Przechwyty', verbose_name='PR')),
                ('blck', models.PositiveIntegerField(default=0, help_text='Bloki', verbose_name='BL')),
                ('ball_loos', models.PositiveIntegerField(default=0, help_text='Straty', verbose_name='ST')),
                ('foul_def', models.PositiveIntegerField(default=0, help_text='Faule defensywne', verbose_name='FA DF')),
                ('foul_off', models.PositiveIntegerField(default=0, help_text='Faule ofensywne', verbose_name='FA OF')),
                ('foul_unsport', models.PositiveIntegerField(default=0, help_text='Faule niesportowe', verbose_name='FA N')),
                ('foul_tech', models.PositiveIntegerField(default=0, help_text='Faule techniczne', verbose_name='FA T')),
                ('foul_disq', models.PositiveIntegerField(default=0, help_text='Faule dyskwalifikujące', verbose_name='FA D')),
                ('time', models.PositiveIntegerField(default=0, help_text='Czas na boisku', verbose_name='T')),
                ('game', models.ForeignKey(help_text='Mecz', on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('player', models.ForeignKey(help_text='Gracz', on_delete=django.db.models.deletion.CASCADE, to='mysite.player')),
            ],
            options={
                'db_table': 'player_statistics',
                'ordering': ['-game__id', '-player__team'],
                'unique_together': {('player', 'game')},
            },
        ),
    ]
