# Generated by Django 3.1.7 on 2021-04-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstats', '0004_auto_20210409_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='shot_3_pts_ok',
            field=models.PositiveIntegerField(default=0, verbose_name='RZ3 O'),
        ),
    ]
