# Generated by Django 3.1.7 on 2021-04-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstats', '0005_auto_20210420_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='ast',
            field=models.PositiveIntegerField(default=0, help_text='Asysty', verbose_name='AS'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='ball_loos',
            field=models.PositiveIntegerField(default=0, help_text='Straty', verbose_name='ST'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='blck',
            field=models.PositiveIntegerField(default=0, help_text='Bloki', verbose_name='BL'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='foul_def',
            field=models.PositiveIntegerField(default=0, help_text='Faule defensywne', verbose_name='FA DF'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='foul_disq',
            field=models.PositiveIntegerField(default=0, help_text='Faule dyskwalifikujące', verbose_name='FA D'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='foul_off',
            field=models.PositiveIntegerField(default=0, help_text='Faule ofensywne', verbose_name='FA OF'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='foul_tech',
            field=models.PositiveIntegerField(default=0, help_text='Faule techniczne', verbose_name='FA T'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='foul_unsport',
            field=models.PositiveIntegerField(default=0, help_text='Faule niepsortowe', verbose_name='FA N'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='reb_def',
            field=models.PositiveIntegerField(default=0, help_text='Zbiórki obrona', verbose_name='ZB D'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='reb_off',
            field=models.PositiveIntegerField(default=0, help_text='Zbiórki atak', verbose_name='ZB O'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='shot_1_pts_ok',
            field=models.PositiveIntegerField(default=0, help_text='Rzuty celne za 1 pkt', verbose_name='RZ1 O'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='shot_1_pts_total',
            field=models.PositiveIntegerField(default=0, help_text='Rzuty ogółem za 1 pkt', verbose_name='RZ1 T'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='shot_2_pts_ok',
            field=models.PositiveIntegerField(default=0, help_text='Rzuty celne za 2 pkt', verbose_name='RZ2 O'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='shot_2_pts_total',
            field=models.PositiveIntegerField(default=0, help_text='Rzuty ogółem za 2 pkt', verbose_name='RZ2 T'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='shot_3_pts_ok',
            field=models.PositiveIntegerField(default=0, help_text='Rzuty celne za 3 pkt', verbose_name='RZ3 O'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='shot_3_pts_total',
            field=models.PositiveIntegerField(default=0, help_text='Rzuty ogółem za 3 pkt', verbose_name='RZ3 T'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='stl',
            field=models.PositiveIntegerField(default=0, help_text='Przechwyty', verbose_name='PR'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='time',
            field=models.PositiveIntegerField(default=0, help_text='Czas na boisku', verbose_name='T'),
        ),
    ]
