# Generated by Django 3.1.7 on 2021-04-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
        ('game', '0001_initial'),
        ('playerstats', '0006_auto_20210421_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='game',
            field=models.ForeignKey(help_text='Mecz', on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='player',
            field=models.ForeignKey(help_text='Gracz', on_delete=django.db.models.deletion.CASCADE, to='mysite.player'),
        ),
    ]
