# Generated by Django 3.1.7 on 2021-04-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstats', '0007_auto_20210422_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='foul_unsport',
            field=models.PositiveIntegerField(default=0, help_text='Faule niesportowe', verbose_name='FA N'),
        ),
    ]
