# Generated by Django 3.1.7 on 2021-04-29 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('forfeit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.season')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='mysite.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='mysite.team')),
            ],
            options={
                'db_table': 'game',
                'unique_together': {('team_1', 'team_2', 'date')},
            },
        ),
    ]
