# Generated by Django 3.1.7 on 2021-03-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='mysite.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='mysite.team'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('team_1', 'team_2', 'date')},
        ),
    ]
