# Generated by Django 3.1.7 on 2021-03-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
        ('game', '0002_auto_20210308_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='forfeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.team'),
        ),
    ]
